### ISSUE TITLE
书签栏的大小设置

### ISSUE THREAD

**Issue by Hyphon** [Developer27149/Erin#1]
首先感谢创造了非常好用的工具！另外个人觉得底部书签栏的尺寸有点小，能否允许用户进行一些页面参数的设置呢？

比如搜索栏的 width, height；书签栏的 width, height；书签栏 icon 的 size 等等

**Comment by AaronConlon** [comment]
> 首先感谢创造了非常好用的工具！另外个人觉得底部书签栏的尺寸有点小，能否允许用户进行一些页面参数的设置呢？
> 
> 比如搜索栏的 width, height；书签栏的 width, height；书签栏 icon 的 size 等等

哈哈，很不错的建议，下个版本我会加上自定义快捷键和大小设置上去！

**Comment by AaronConlon** [comment]
Hello 已经修复了

**Comment by Hyphon** [comment]
测试了下很不错！非常感谢 ：）
